baseURL = "/"
languageCode = "en-us"
title = "Linuxo blog"
theme = "ananke"
SectionPagesMenu = "main"

[params]
# env = "production"
 custom_css = ["css/custom.css"]
 staticman_api = "https://api.staticman.net/v2/entry/tomaja-linuxo/lhb-comments/master" #Add staticman API URL to enable staticman comments
